working_path=workspace_temp
log_file_name=setup_environment
local_config_file_name=local_config
graphql_schema_file_name=schema
python_virtual_bash=.venv/bin/activate
python_virtual_ps1=.venv/bin/Activate.ps1
python_module=py