python_module=codename_snake
resources_path=resources
working_path=workspace_temp
log_file_name=python_snake
local_config_file_name=local_config
graphql_schema_file_name=schema
python_virtual_bash=.venv/bin/activate
python_virtual_ps1_osx=.venv/bin/Activate.ps1
python_virtual_ps1_linux=.venv/bin/activate.ps1
python_virtual_ps1_win=.venv/Scripts/Activate.ps1