name: PR Validation

on:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
    
    - name: Run pytest
      run: |
        uv run pytest

    - name: Run flake8
      run: |
        uv run flake8 codename_snake