name: PR Validation

on:
  pull_request:
    types: [ opened, ready_for_review, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
    
    - name: Run pytest
      run: |
        uv run pytest

    - name: Run ruff check
      run: |
        uv run ruff check src/mega_snake --output-format=concise

    - name: Run mypy
      run: |
        uv run mypy --show-column-numbers --no-error-summary src/mega_snake